[package]
name = "oxipot"
version = "0.1.0"
edition = "2021"
authors = ["Pouriya Jamshidi"]

[dependencies]
log = "*"
env_logger = "*"
serde = { version = "*", features = ["derive"] }
reqwest = { version = "*", features = ["json", "blocking"] }
tokio = { version = "*", features = ["full"] }
chrono = "*"
once_cell = "*"
