services:
  oxipot:
    image: oxipot:latest
    ports:
      - 23:2223
    volumes:
      - /var/log/oxipot/oxipot.db:/oxipot/oxipot.db:rw
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
