services:
  oxipot:
    build:
      context: .
      dockerfile: Dockerfile
    image: oxipot:latest
    ports:
      - 23:2223
    volumes:
      - /var/log/oxipot/:/oxipot/db/
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
